### ISSUE TITLE
Website client shop UI

### ISSUE THREAD

**Issue by ricardobrg** [tiki/website#57]
### Description

Create the UI that will be used as the model for all client's data shop and plan it's deployment for multiple clients.

### Issues

- [x] tiki/website-client-shop/issues/27
- [x] tiki/website-client-shop/issues/1
- [x] tiki/website-client-shop/issues/2
- [x] tiki/website-client-shop/issues/3
- [x] tiki/website-client-shop/issues/4
- [x] tiki/website-client-shop/issues/5
- [x] tiki/website-client-shop/issues/6
- [x] tiki/website-client-shop/issues/7
- [x] tiki/website-client-shop/issues/8
- [x] tiki/website-client-shop/issues/10
- [x] tiki/website-client-shop/issues/13
- [x] tiki/website-client-shop/issues/14
- [x] tiki/website-client-shop/issues/15
- [x] tiki/website-client-shop/issues/16
- [x] tiki/website-client-shop/issues/18
- [x] tiki/website-client-shop/issues/21
- [x] tiki/website-client-shop/issues/23
- [x] tiki/website-client-shop/issues/24
- [x] tiki/website-client-shop/issues/26
