### ISSUE TITLE
Client Shop UI Improvements

### ISSUE THREAD

**Issue by ricardobrg** [tiki/website#58]
### Description

Improve the Client Shop UI with new features and optimizations:

### Issues

- [x] tiki/website-client-shop/issues/33
- [x] tiki/website-client-shop/issues/34
- [ ] tiki/website-client-shop/issues/30
- [ ] tiki/website-client-shop/issues/9
- [ ] tiki/website-client-shop/issues/31
